<?php
namespace app\server\http\admin\user;

use Small\annotation\parser\Auth;
use Small\annotation\parser\Inject;
use Small\annotation\parser\Method;
use Small\lib\util\Str;
use Small\model\models\UserModel;
use Small\server\http\HttpController;
use Small\lib\auth\User;

/**
 * @Auth(group="admin")
 * Class indexController
 * @package app\server\http\admin\user
 */
class indexController extends HttpController{

    /**
     * @Inject(User::class)
     * @var
     */
    public $user;

    public function index(...$args)
    {
        //return parent::index($args); // TODO: Change the autogenerated stub
        $pageUrl = $list = [];
        $um = new UserModel();
        $db = $um;
        // <---- begin 上级UID
        $parent_uid = $this->getQueryString("uid");
        if($parent_uid>0){
            $parent = $um->where("u.uid", $parent_uid)
                //->whereFindInSet($this->user["uid"], "u.parents_uid")
                ->select([
                    "u.*",
                    "g.group_name, g.group_type"
                ])
                ->first();
            //如果找不到指定会员，则当前的父级会员是自己所登录的账号
            $parent = !empty($parent) ? $parent : $this->user;
        }else{
            $parent = $this->user;
        }
        if(!empty($parent)){
            $pageUrl['uid'] = $parent_uid;
            //查出所有上级会员
            if(!empty($parent["parents_uid"])){
                $parents = $um->whereIn("u.uid", $parent["parents_uid"])
                    ->orderBy("u.floor", "asc")
                    ->select("u.uid, u.username, u.nickname, u.phone")
                    ->get();
                foreach ($parents as &$p){
                    $p['nickname'] = Str::base64Decode($p['nickname']);
                }
                $this->view->assign("parents", $parents);
            }
            if($parent['group_id']==2){
                $db = $db->where("u.parent_uid", $parent['uid']);
            }
        }
        $parent['nickname'] = Str::base64Decode($parent['nickname']);
        $this->view->assign("parent", $parent);
        // <---- end 父级会员条件
        // <---- begin 搜索
        $keyword = $this->getQueryString('keyword');
        if(!empty($keyword)){
            $pageUrl['keyword'] = $keyword;
            if(Str::isPhoneNumber($keyword)){
                $db = $db->where("u.phone", $keyword);
            }else{
                $db = $db->where(function ($q) use($keyword){
                    $q->whereLike("u.username", "%{$keyword}%")
                        ->orWhereLike("u.nickname", "%{$keyword}%");
                });
            }
        }
        // <---- end 搜索

        // <---- begin 会员类型条件
        $group = $this->getQueryString("group");
        $group = is_numeric($group) && $group>0 ? $group : 0;
        if(!empty($group)){
            $pageUrl['group'] = $group;
            $db = $db->where("u.group_id", $group);
        }
        // <---- end 会员类型条件

        // <---- begin 会员状态
        $frozen = $this->getQueryString("frozen");
        $frozen = in_array($frozen, [1, 0]) ? $frozen : null;
        if(!is_null($frozen)){
            $pageUrl['frozen'] = $frozen;
            $db = $db->where("u.frozen", $frozen);
        }
        // <---- end 会员状态
        //最终查询字段
        $db = $db
            ->leftJoin("user p", ["u.parent_uid", "p.uid"])
            ->select([
                "u.*",
                "g.group_name, g.group_type",
                "p.nickname p_nick, p.phone p_phone"
            ]);
        //print_r($db->compileToQueryString());exit;
        //行数
        $rows = $db->rows();
        //总页数
        $pages = 0;
        //当前页
        $page = $this->getQueryString("page", 1);
        $page = is_numeric($page) && $page>0 ? $page : 1;
        $total = $this->getQueryString("total", 30);
        $pageUrl["total"] = $total;
        if($rows>0){
            $pages = ceil($rows/$total);
            $page = $page>$pages ? $pages : $page;
            $offset = $total*($page-1);
            $list = $db->orderBy("u.uid", "desc")
                ->get($total, $offset);
            foreach ($list as &$item){
                $item['nickname'] = Str::base64Decode($item['nickname']);
                $item['p_nick'] = Str::base64Decode($item['p_nick']);
            }
        }
        //当前地址
        $self_url = "/admin/user";
        $url = url($self_url)."?".makeUrlQuery($pageUrl);
        $this->view->assign('page', compact('pages', 'page', 'rows', 'url'));
        $this->view->assign('list', $list);
        $this->view->assign('pageUrl', $pageUrl);
        $this->view->assign('self', $self_url);
        //用户分组
        $groups = $um->mainQuery()->newQuery()->from("user_group")->get();
        $this->view->assign('userGroup', $groups);
    }

    /**
     * 冻结/解冻
     * @Method("GET")
     */
    public function frozen(){
        //权限判断
        $uid = !empty($uid) ? $uid : $this->getQueryString("uid");
        $uid = is_numeric($uid) && $uid>0 ? $uid : 0;
        $bool = 1;
        $message = "UID参数错误";
        $um = new UserModel();
        if($uid>0){
            $db = $um->getQuery()
                ->where("uid", $uid)
                //自己无法冻结自己的账号
                ->where("uid", "!=", $this->user['uid'])
                //超级管理员不可冻结账号
                ->where("founder", 0);
            $data = $db->first();
            if(!empty($data)){
                $data['nickname'] = Str::base64Decode($data['nickname']);
                $this->view->assign('data', $data);
            }else{
                $this->response('找不到账号');
            }
        }else{
            $this->response('参数错误');
        }
    }

    /**
     * @Method("AJAX_POST")
     */
    public function frozenSave(){
        $uid = $this->getPostData("uid", null, '缺少UID参数');
        $uid = is_numeric($uid) && $uid>0 ? $uid : 0;
        if($uid>0){
            $um = new UserModel();
            $db = $um->getQuery()
                ->where("uid", $uid)
                //自己无法冻结自己的账号
                ->where("uid", "!=", $this->user['uid'])
                //超级管理员不可冻结账号
                ->where("founder", 0);
            $data = $db->first();
            if(!empty($data)){
                $type = $this->getPostData('type');
                $type = in_array($type, ['unlock', 'single', 'recommend', 'team']) ? $type : null;
                if(is_null($type)){
                    $this->response('参数错误');
                }
                $u = new User(false);
                //二维密码验证
                $session_sp = Request::getSession("admin_sp");
                $sp = $this->getPOSTData("sp", null, empty($session_sp) ? "请填写安全密码" : null);
                $sp = empty($sp) ? $session_sp : $sp;
                //验证个人安全密码
                if(User::checkSafePassword($this->user["uid"], $sp)){
                    $this->response("管理员安全密码错误！");
                }
                Request::setSession("admin_sp", $sp);
                $note = $this->getPostData('note', null, $type!='unlock' ? '缺少冻结备注' : null);
                if($type=='unlock'){
                    $db = $um->mainQuery()
                        ->where('uid', $uid);
                    if($db->update(['frozen'=>0])){
                        $this->response(0, '操作成功');
                    }else{
                        $this->response('操作失败');
                    }
                }else{
                    $db = $um->mainQuery();
                    if($type=='single'){
                        $db->where('uid', $uid);
                    }elseif($type=='recommend'){
                        $db->where('uid', $uid)
                            ->orWhere("parent_uid", $uid);
                    }else{
                        $db->where('uid', $uid)
                            ->orWhereFindInSet($uid, "parents_uid");
                    }
                    if($db->update(['frozen'=>1])){
                        //记录
                        $fhm = new FrozenHistoryModel();
                        $log = [
                            "uid"   => $uid,
                            "reason"    => $note
                        ];
                        @$fhm->mainQuery()->insert($log);
                        $this->response(0, '共冻结账号：'.$db->getAffectRows().'个');
                    }else{
                        $this->response('操作失败');
                    }
                }
            }else{
                $this->response('找不到账号');
            }
        }else{
            $this->response('参数错误');
        }
    }

    /**
     * 修改部分资料
     * @Method("GET")
     */
    public function edit(){
        $uid = $this->getQueryString('uid', null, '缺少UID参数');
        $uid = is_numeric($uid) && $uid>0 ? $uid : 0;
        if($uid>0){
            $um = new UserModel();
            $edit = $um->where("u.uid", $uid)->first();
            if(!empty($edit)){
                $edit['nickname'] = Str::base64Decode($edit['nickname']);
                $this->assign('data', $edit);
            }else{
                $this->response("找不到账号数据！");
            }
        }else{
            $this->response('错误的UID参数');
        }
    }

}