<?php
namespace app\http\files\upload;

use Small\annotation\parser\Auth;
use Small\annotation\parser\Inject;
use Small\annotation\parser\Method;
use Small\http\HttpController;
use Small\lib\auth\User;

/**
 * @Auth()
 * Class indexController
 * @package app\web\http\files\upload
 */
class indexController extends HttpController {

    /**
     * @Inject(User::class)
     * @var array
     */
    public $user;

    /**
     * @Method("POST")
     * @param mixed ...$args
     * @return mixed|void
     */
    public function index(...$args)
    {
        //parent::index(); // TODO: Change the autogenerated stub
        //自动识别
        if(!empty($_FILES)){
            //如果是表单文件POST，则使用文件上传形式
            $api = new filesController();
            $api->user = $this->user;
            $api->response = $this->response;
            $api->index();
        }else{
            //否则使用base64识别
            $api = new base64Controller();
            $api->user = $this->user;
            $api->response = $this->response;
            $api->index();
        }
    }
}