<?php
namespace app\server;

/**
 * 接收到新消息
 * Class messageController
 * @package app\server
 */
class messageController extends \Small\server\controller\messageController {

    /**
     * 默认使用父级处理
     * @param mixed ...$args
     * @return mixed|void
     */
    public function index(...$args)
    {
        parent::index($args); // TODO: Change the autogenerated stub
    }
}