<?php
namespace app\server\websocket;

/**
 * [http, websocket]客户端连接关闭
 * Class CloseController
 * @package app\server\websocket
 */
class CloseController extends \Small\server\websocket\CloseController {

    /**
     * 默认使用父级处理
     * @param mixed ...$args
     * @return mixed|void
     */
    public function index(...$args)
    {
        parent::index($args); // TODO: Change the autogenerated stub
    }
}