<?php
namespace app\server\websocket;

/**
 * 接收到新消息
 * Class MessageController
 * @package app\server\websocket
 */
class MessageController extends \Small\server\websocket\MessageController {

    /**
     * 默认使用父级处理
     * @param mixed ...$args
     * @return mixed|void
     */
    public function index(...$args)
    {
        parent::index($args); // TODO: Change the autogenerated stub
    }
}