<?php
namespace app\server\http\web;

use app\server\http\RequestController;
use Small\lib\httpMessage\Request;
use Small\model\models\UserModel;

class indexController extends RequestController{

    public function index(...$args)
    {
        //parent::index($args); // TODO: Change the autogenerated stub
        /*
        $m = new UserModel();
        $row = $m->mainQuery()
            ->where('uid', 2)
            ->first();
        return $row;
        */
    }
}