<?php
namespace app\server\http\web;

use app\server\http\RequestController;

class indexController extends RequestController{

    public function index(...$args)
    {
        //parent::index($args); // TODO: Change the autogenerated stub

    }
}