<?php
/**
 * Created by PhpStorm.
 * User: Hunter
 * Date: 2019-03-14
 * Time: 10:33
 */
namespace app\server\http\web;

use EasySwoole\VerifyCode\Conf;
use EasySwoole\VerifyCode\VerifyCode;
use Small\server\http\HttpController;
use Small\server\session\Session;

class vcController extends HttpController {

    /**
     * @param mixed ...$args
     * @return mixed|\Small\server\http\Response|void
     */
    public function index(...$args)
    {
        //return parent::index($args); // TODO: Change the autogenerated stub
        $Conf = new Conf();
        // 开启或关闭混淆曲线
        //$Conf->setUseCurve();
        // 开启或关闭混淆噪点
        //$Conf->setUseNoise();
        // 设置图片的宽度
        $Conf->setImageWidth(80);
        // 设置图片的高度
        $Conf->setImageHeight(26);
        // 设置生成字体大小
        $Conf->setFontSize(12);
        // 设置生成验证码位数
        $Conf->setLength(4);
        //
        $VCode = new VerifyCode($Conf);
        //
        $Code = $VCode->DrawCode();
        //
        $Code->getImageBase64();
        //获取码
        //Request::setSession("verify_code", $Code->getImageCode());
        $codeValue = $Code->getImageCode();
        //将验证码保存到Session(redis保存)
        $session = new Session($this);
        $session->setVerifyCode($codeValue);
        //输出验证码图片
        $this->response->withContent($Code->getImageByte())
            ->withHeader("Content-Type", $Code->getImageMime())
            ->send();
    }
}