<?php
namespace app\http\files;

use app\annotation\parser\Auth;
use app\annotation\parser\Inject;
use app\annotation\parser\Method;
use app\http\HttpController;
use app\model\models\FilesModel;
use app\lib\auth\User;

/**
 * @Auth()
 * Class indexController
 * @package app\http\files
 */
class indexController extends HttpController {

    /**
     * @Inject(User::class)
     * @var array
     */
    public $user;

    /**
     * @Method("GET")
     * @param mixed ...$args
     * @return mixed|void
     */
    public function index(...$args)
    {
        //parent::index(); // TODO: Change the autogenerated stub
        $m = new FilesModel();
        //仅查询自己的文件
        $db = $m->mainQuery()
            ->where('uid', $this->user['uid']);
        //文件管理器
        $year = $this->getQueryString("year");
        $year = is_numeric($year) && $year>0 && $year<=date("Y", time()) ? intval($year) : 0;
        if($year>0){
            $db->whereRaw("year(`time`)={$year}");
            $month = $this->getQueryString("month");
            $month = is_numeric($month) && $month>0 && $month<=12 ? intval($month) : 0;
            if($month>0){
                $db->whereRaw("month(`time`)={$month}");
                $day = $this->getQueryString("day");
                $day = is_numeric($day) && $day>0 && $day<=31 ? intval($day) : 0;
                if($day>0){
                    $db->whereRaw("day(`time`)={$day}");
                }
            }
            $page = $this->getQueryString("page", 1);
            $page = is_numeric($page) && $page>0 ? $page : 1;
            $rows = $db->rows();
            if($rows>0){
                $total = 20;
                $pages = ceil($rows/$total);
                $offset = $total*($page-1);
                $list = $db->orderBy("`time`", "desc")->select("`name`, `url`, `file_hash`, `time`")->get($total, $offset);
                foreach ($list as &$item){
                    $item['src'] = attachmentUrlRebuild($item['url']);
                    $item['value'] = $item['url'];
                    unset($item['url']);
                }
                $this->response([
                    'rows'  => $rows,
                    'page'  => intval($page),
                    'pages' => intval($pages),
                    'list'  => $list
                ]);
            }
        }
        $this->response([
            'rows'  => 0,
            'page'  => 1,
            'pages' => 0,
            'list'  => []
        ]);
    }

}