<?php
namespace app\websocket;

/**
 * 连接关闭
 * Class closeController
 * @package app\websocket
 */
class closeController extends \Small\websocket\closeController {

    /**
     * 默认使用父级处理
     * @param mixed ...$args
     * @return mixed|void
     */
    public function index(...$args)
    {
        parent::index($args); // TODO: Change the autogenerated stub
    }
}