<?php
namespace app\server\http\admin;

use Small\server\http\RequestController;
use Small\annotation\parser\Auth;
use Small\annotation\parser\Method;

/**
 * @Auth()
 * Class indexController
 * @package app\server\http\admin
 */
class indexController extends RequestController {

    /**
     * @Method("GET")
     * @param mixed ...$args
     * @return mixed|void
     */
    public function index(...$args)
    {
        //parent::index($args); // TODO: Change the autogenerated stub
        return '123';
    }
}