<?php
namespace app\server\http\admin;

use Small\annotation\parser\Inject;
use Small\lib\util\File;
use Small\server\http\HttpController;
use Small\annotation\parser\Auth;
use Small\annotation\parser\Method;
use Small\lib\auth\User;

/**
 * @Auth(group="admin")
 * Class indexController
 * @package app\server\http\admin
 */
class indexController extends HttpController {

    /**
     * @Inject(User::class)
     * @var
     */
    public $user;

    /**
     * @Method("GET")
     * @param mixed ...$args
     * @return mixed|void
     */
    public function index(...$args)
    {
        //parent::index($args); // TODO: Change the autogenerated stub
        //return $this->user;
        $parts = File::getDirs(__DIR__, null);
        $menus = [];
        foreach ($parts as $p){
            if(is_file($p['path']."/menus.php")){
                $menus[] = require $p['path']."/menus.php";
            }
        }
        $this->view->assign('menus', $menus);
    }

    /**
     * @Method({"GET", "POST"})
     */
    public function logout(){
        $u = new User(false, 86400, $this);
        $u->logout();
        $this->redirect("login");
    }
}