<?php
namespace app\server\http\admin;

use Small\annotation\parser\Method;
use Small\lib\auth\User;
use Small\server\http\RequestController;
use Small\server\session\Session;

/**
 * Class loginController
 * @package app\server\http\admin
 */
class loginController extends RequestController{

    /**
     * 后台登录
     * @param mixed ...$args
     * @return mixed|void
     */
    public function index(...$args)
    {
        //return parent::index($args); // TODO: Change the autogenerated stub
    }

    /**
     * 登录提交入口
     * @Method("AJAX_POST")
     */
    public function submit(){
        $username = $this->getPostData('trim:username');
        if(empty($username)){
            return $this->response(lang("framework.login.101"));
        }
        $password = $this->getPostData('password');
        if(empty($password)){
            return $this->response(lang("framework.login.102"));
        }
        $verify_code = $this->getPostData('trim:verify_code');
        if(empty($verify_code)){
            return $this->response(lang("framework.login.103"));
        }
        //判断验证码是否正确
        $session = new Session($this);
        if(!$session->matchVerifyCode($verify_code)){
            return $this->response('验证码填写错误');
        }
        $u = new User(false, 86400, $this);
        if($u->login($username, $password)){
            $info = $u->userInfo;
            if($info['group_type']=='admin'){
                return $this->response(0, [
                    "token"     => $info['token'],
                    "callback_url" => url("/admin")
                ]);
            }else{
                $u->logout();
                return $this->response(lang("framework.auth.105"));
            }
        }else{
            return $this->response($u->errorInfo);
        }
    }
}